name: 'Deploy'

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  
jobs:
  call-workflow:
    strategy:
      matrix:
        target: [./, ./common, ./network]
    uses: ScalefreeCOM/TFAutomation_templates/.github/workflows/terraform-deploy.yml@main
    with:
      tf_version: 1.5.4
      approvers: it
      issue-title: Deploying important stuff
      working_directory: ${{ matrix.target }}
    secrets: inherit
    permissions:
      contents: read
      issues: write
      pull-requests: write