name: 'Push'

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      region:
        type: string
        default: "eu-west-1"
      ecr_repo:
        type: string
        required: true
      image_tag:
        type: string
        default: latest
      push_to_aws:
        type: boolean
        default: false
    secrets:
      TFAUTOMATION_AWS_ACCESS_KEY:
         required: true
      TFAUTOMATION_AWS_SECRET_ACCESS_KEY:
         required: true
      AWS_OIDC_ROLE:
         required: true
  workflow_dispatch:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      region:
        type: string
        default: "eu-west-1"
      ecr_repo:
        type: string
        required: true
      image_tag:
        type: string
        default: latest
      push_to_aws:
        type: boolean
        default: false
                
jobs:
  push:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push image to Amazon ECR
        if: ${{ github.event_name == 'push' || inputs.push_to_aws }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build --build-arg="ssh_pub_key=${{ secrets.SSH_KEY }}" --no-cache -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Build image # For manually checking if docker build is working.
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.push_to_aws }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build --build-arg="ssh_pub_key=${{ secrets.SSH_KEY }}" --no-cache -t $ECR_REPOSITORY .
  
