name: 'Build'


on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      region:
        type: string
        default: "eu-west-3"
      tf_version:
        type: string
        required: true
      working_directory:
        type: string
        required: true
    secrets:
       TFAUTOMATION_AWS_ACCESS_KEY:
         required: true
       TFAUTOMATION_AWS_SECRET_ACCESS_KEY:
         required: true
         
        
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.TFAUTOMATION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TFAUTOMATION_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}
    
      - name: Terraform fmt
        id: fmt
        run: terraform fmt
    
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Validate
        id: validate
        run: terraform validate
    
      - name: Terraform Plan
        id: plan
        run: |
          TF_EXIT_CODE=$(terraform plan -out=tfplan -detailed-exitcode | grep -oP '(?<=::debug::exitcode: )\d+' || echo 0)
          
          TF_PLAN=$(terraform plan -out=tfplan)
          
          
          echo "TF_EXIT_CODE=$TF_EXIT_CODE" >> $GITHUB_ENV
          echo "Erste Option: $TF_EXIT_CODE"
          echo "Zweite Option: TF_EXIT_CODE"
          echo "Dritte Option: env.TF_EXIT_CODE"
          echo "$TF_PLAN"
        
      - name: Print exit Code
        run: | 
          echo "Terraform Exit Code: $TF_EXIT_CODE"
  
        
  test:
    runs-on: ${{ inputs.runs-on }}
    needs: build
    
    steps:
    
    - name: No changes
      if: ${{ env.TF_EXIT_CODE == 0 }}
      run: echo "There no are changes"
      
    - name: Error
      if: ${{ env.TF_EXIT_CODE == 1 }}
      run: echo "There is an Error"
      
    - name: Changes
      if: ${{ env.TF_EXIT_CODE == 2 }}
      run: echo "There are changes"
