name: 'Deploy'

on:
  workflow_call:
    inputs:
      region:
        type: string
        default: "eu-west-3"
      tf_version:
        type: number
        required: true
    secrets:
       AWS_ACCESS_KEY:
         required: true
       AWS_SECRET_ACCESS_KEY:
         required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    # Checkout the repo
    - uses: actions/checkout@v3

    # Configure AWS credentials
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: inputs.tf_version

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan
        
  deploy:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: build
      
    steps:
    - uses: actions/checkout@v3

     # Configure AWS credentials
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:  ${{ inputs.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: inputs.tf_version
      
    - name: Terraform Init
      run: terraform init
        
    - name: Terraform Apply
      run: terraform apply -auto-approve
