name: 'Deploy'

on:
  workflow_call:
    inputs:
      runs-on: 
        type: string
        default: ubuntu-latest
      region:
        type: string
        default: "eu-west-3"
      cloud_provider:
        type: string
        default: "aws"
      tf_version:
        type: string
        required: true
      working_directory:
        type: string
        required: true
    secrets:
       TFAUTOMATION_AWS_ACCESS_KEY:
         required: true
       TFAUTOMATION_AWS_SECRET_ACCESS_KEY:
         required: true
        
jobs:        
  deploy:
    runs-on: ${{ inputs.runs-on }}

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
        
    steps:   
    - uses: actions/checkout@v3

     # Configure AWS credentials
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id:  ${{ secrets.TFAUTOMATION_AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.TFAUTOMATION_AWS_SECRET_ACCESS_KEY }}
        aws-region:  ${{ inputs.region }}

      
    - name: 'Az CLI login'
      if: inputs.cloud_provider == 'azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.TFAUTOMATION_AZURE_CLIENT_ID}}
        tenant-id: ${{ secrets.TFAUTOMATION_AZURE_TENANT_ID}}
        subscription-id: ${{ secrets.TFAUTOMATION_AZURE_SUBSCRIPTION_ID }}

    - name: 'Authenticate to Google Cloud'
      if: inputs.cloud_provider == 'gcp'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/472159367072/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc'
        service_account: 'github-actions@scalefree-edw-test.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf_version }}
      
    - name: Terraform Init
      run: terraform init
        
    - name: Terraform Apply
      run: terraform apply -auto-approve
