name: 'Build'


on:
  workflow_call:
    inputs:
      region:
        type: string
        default: "eu-west-3"
    secrets:
      access-key:
        required: true
      secret-access-key:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access-key }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: ${{ inputs.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4
    
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
    
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Validate
        id: validate
        run: terraform validate
    
      - name: Terraform Plan
        id: plan
        run: terraform plan
