name: 'test'

on:
  workflow_call:
    outputs:
        dbt-test-result: 
          value: ${{ jobs.collect-job-results.outputs.dbt-test-result }}
        dbt-test-result2: 
          value: ${{ jobs.collect-job-results.outputs.dbt-test-result2 }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "test"
  test2:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: exit 1

  collect-job-results:
    if: always()
    needs: [ test, test2 ]

    runs-on: ubuntu-latest
    outputs:
      dbt-test-result: ${{ steps.results.outputs.dbt-test-result}}
      dbt-test-result2: ${{ steps.results.outputs.dbt-test-resultt}}
    steps:
    - name: Collect results
      id: results
      run: |
        echo "dbt-test-result=${{ needs.test.result }}" >> $GITHUB_OUTPUT
        echo "dbt-test-resultt=${{ needs.test2.result }}" >> $GITHUB_OUTPUT


        

  
