name: 'test'

on:
  workflow_call:
    outputs:
        dbt-test-result: 
          value: ${{ jobs.collect-job-results.outputs.dbt-test-result }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "test"
      
  collect-job-results:
    if: always()
    needs: test

    runs-on: ubuntu-latest
    outputs:
      dbt-test-result: ${{ steps.results.outputs.dbt-test-result}}
    steps:
    - name: Collect results
      id: results
      run: |
        echo "dbt-test-result=${{ needs.test.result }}" >> $GITHUB_OUTPUT


        

  
